import { NextPage } from 'next';
import Head from 'next/head'
import LayoutHomePageProps from '../../interfaces/layouts/home'
import Nav from '../components/nav';
import NavMobile from '../components/mobileNav';
import { useMediaQuery } from 'react-responsive';


const LayoutHomePage: NextPage<LayoutHomePageProps> = ({ children, ...props }: LayoutHomePageProps) => {

  const isMobile = useMediaQuery({ maxWidth: 767 });

  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name={props.descripcion} content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='m-0 p-0'>
        {isMobile ? (
          <NavMobile /> // Mostrar componente para pantallas pequeñas
        ) : (
          <Nav /> // Mostrar componente para pantallas grandes
        )}

        {children}
      </main>
    </>
  );
};

export default LayoutHomePage;